### ISSUE TITLE
Access policy is not updated

### ISSUE THREAD

**Issue by shreben** [aws-controllers-k8s/opensearchservice-controller#36] opened 2022-09-16 12:23 UTC
Hi team
I ran into the following issue.
Opensearchservice controller doesn't update an access policy after it was changed in kubernetes.
There is a message in the log below "not implemented". Does it mean this functionality is not present at the moment?
Thanks for taking a look.

Here is the details.
Controller image  `public.ecr.aws/aws-controllers-k8s/opensearchservice-controller:v0.0.14`

Existing access policy copied from Opensearch service AWS console:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::xxxxxxxxxxxx:role/pod-role/iamr-test-role",
          "arn:aws:iam::xxxxxxxxxxxx:role/pod-role/iamr-test-role-2"
        ]
      },
      "Action": "es:*",
      "Resource": "arn:aws:es:eu-west-1:xxxxxxxxxxxx:domain/os-test/*"
    }
  ]
}
```
Existing k8s resource:
```
$ k describe domains.opensearchservice.services.k8s.aws 
Name:         os-test
Namespace:    default
...
API Version:  opensearchservice.services.k8s.aws/v1alpha1
Kind:         Domain
Metadata:
  Creation Timestamp:  2022-09-16T10:00:40Z
  Finalizers:
    finalizers.opensearchservice.services.k8s.aws/Domain
  Generation:  7
...
Spec:
  Access Policies:  {"Statement":[{"Action":"es:*","Effect":"Allow","Principal":{"AWS":["arn:aws:iam::xxxxxxxxxxxx:role/pod-role/iamr-test-role"]},"Resource":"arn:aws:es:eu-west-1:xxxxxxxxxxxx:domain/os-test/*"}],"Version":"2012-10-17"}
  Advanced Options:
    override_main_response_version:          true
    rest.action.multi.allow_explicit_index:  true
  Advanced Security Options:
    Enabled:                         false
    Internal User Database Enabled:  false
  Auto Tune Options:
  Cluster Config:
    Cold Storage Options:
      Enabled:                 false
    Dedicated Master Enabled:  false
    Instance Count:            2
    Instance Type:             t3.small.search
    Warm Enabled:              false
    Zone Awareness Config:
      Availability Zone Count:  2
    Zone Awareness Enabled:     true
  Cognito Options:
    Enabled:           true
    Identity Pool ID:  eu-west-1:....................
    Role ARN:          arn:aws:iam::xxxxxxxxxxxx:role/service-role/iamr-cognito
    User Pool ID:      eu-west-1_xxxxxxx
  Domain Endpoint Options:
    Custom Endpoint Enabled:  false
    Enforce HTTPS:            true
    Tls Security Policy:      Policy-Min-TLS-1-0-2019-07
  Ebs Options:
    Ebs Enabled:  true
    Volume Size:  20
    Volume Type:  gp2
  Encryption At Rest Options:
    Enabled:       true
    Kms Key ID:    arn:aws:kms:eu-west-1:xxxxxxxxxxxx:key/xxxxxxxxxxxxxxxxxx
  Engine Version:  OpenSearch_1.1
  Name:            os-test
  Node To Node Encryption Options:
    Enabled:  false
  Tags:
    Key:    Name
    Value:  os-test
  Vpc Options:
    Security Group I Ds:
      sg-xxxxxxxx
      sg-xxxxxxxx
    Subnet I Ds:
      subnet-xxx
      subnet-xxx
Status:
  Ack Resource Metadata:
    Arn:               arn:aws:es:eu-west-1:xxxxxxxxxxxx:domain/os-test
    Owner Account ID:  xxxxxxxxxxxx
    Region:            eu-west-1
  Conditions:
    Last Transition Time:  2022-09-16T12:09:05Z
    Status:                True
    Type:                  ACK.ResourceSynced
    Message:               not implemented
    Status:                True
    Type:                  ACK.Recoverable
  Created:                 true
  Deleted:                 false
  Domain ID:               xxxxxxxxxxxx/os-test
  Endpoints:
    Vpc:       vpc-os-test-xxxx.eu-west-1.es.amazonaws.com
  Processing:  false
  Service Software Options:
    Automated Update Date:  1970-01-01T00:00:00Z
    Cancellable:            false
    Current Version:        R20220323-P5
    Description:            There is no software update available for this domain.
    New Version:            
    Optional Deployment:    true
    Update Available:       false
    Update Status:          COMPLETED
  Snapshot Options:
    Automated Snapshot Start Hour:  0
  Upgrade Processing:               false
Events:                             <none>

```

Controller logs with log level "debug":
```
2022-09-16T12:03:37.493816427Z 2022-09-16T12:03:37.493Z	INFO	ackrt	desired resource state has changed	{"account": "xxxxxxxxxxxx", "role": "", "region": "eu-west-1", "kind": "Domain", "namespace": "default", "name": "os-test", "is_adopted": false, "generation": 7, "diff": [{"Path":{"Parts":["Spec","AccessPolicies"]},"A":"{\"Statement\":[{\"Action\":\"es:*\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::xxxxxxxxxxxx:role/pod-role/iamr-test-role\"]},\"Resource\":\"arn:aws:es:eu-west-1:xxxxxxxxxxxx:domain/os-test/*\"}],\"Version\":\"2012-10-17\"}","B":"{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::xxxxxxxxxxxx:role/pod-role/iamr-test-role\",\"arn:aws:iam::xxxxxxxxxxxx:role/pod-role/iamr-test-role-2\"]},\"Action\":\"es:*\",\"Resource\":\"arn:aws:es:eu-west-1:xxxxxxxxxxxx:domain/os-test/*\"}]}"},{"Path":{"Parts":["Spec","AdvancedSecurityOptions","AnonymousAuthEnabled"]},"A":null,"B":false}]}
2022-09-16T12:03:37.493831025Z 2022-09-16T12:03:37.493Z	DEBUG	ackrt	>>> rm.Update	{"account": "xxxxxxxxxxxx", "role": "", "region": "eu-west-1", "kind": "Domain", "namespace": "default", "name": "os-test", "is_adopted": false, "generation": 7}
2022-09-16T12:03:37.493887543Z 2022-09-16T12:03:37.493Z	DEBUG	ackrt	<<< rm.Update	{"account": "xxxxxxxxxxxx", "role": "", "region": "eu-west-1", "kind": "Domain", "namespace": "default", "name": "os-test", "is_adopted": false, "generation": 7, "latest": {}, "error": "not implemented"}
2022-09-16T12:03:37.493894467Z 2022-09-16T12:03:37.493Z	DEBUG	ackrt	<< r.updateResource	{"account": "xxxxxxxxxxxx", "role": "", "region": "eu-west-1", "kind": "Domain", "namespace": "default", "name": "os-test", "is_adopted": false, "generation": 7, "error": "not implemented"}
2022-09-16T12:03:37.493898515Z 2022-09-16T12:03:37.493Z	DEBUG	ackrt	>> r.ensureConditions	{"account": "xxxxxxxxxxxx", "role": "", "region": "eu-west-1", "kind": "Domain", "namespace": "default", "name": "os-test", "is_adopted": false, "generation": 7}
2022-09-16T12:03:37.493902316Z 2022-09-16T12:03:37.493Z	DEBUG	ackrt	<< r.ensureConditions	{"account": "xxxxxxxxxxxx", "role": "", "region": "eu-west-1", "kind": "Domain", "namespace": "default", "name": "os-test", "is_adopted": false, "generation": 7}
2022-09-16T12:03:37.493906331Z 2022-09-16T12:03:37.493Z	DEBUG	ackrt	< r.Sync	{"account": "xxxxxxxxxxxx", "role": "", "region": "eu-west-1", "kind": "Domain", "namespace": "default", "name": "os-test", "is_adopted": false, "generation": 7, "error": "not implemented"}
2022-09-16T12:03:37.493910218Z 2022-09-16T12:03:37.493Z	DEBUG	ackrt	> r.patchResourceStatus	{"account": "xxxxxxxxxxxx", "role": "", "region": "eu-west-1", "kind": "Domain", "namespace": "default", "name": "os-test", "is_adopted": false, "generation": 7}
2022-09-16T12:03:37.493922295Z 2022-09-16T12:03:37.493Z	DEBUG	ackrt	>> kc.Patch (status)	{"account": "xxxxxxxxxxxx", "role": "", "region": "eu-west-1", "kind": "Domain", "namespace": "default", "name": "os-test", "is_adopted": false, "generation": 7}
2022-09-16T12:03:37.511704554Z 2022-09-16T12:03:37.511Z	DEBUG	ackrt	patched resource status	{"account": "xxxxxxxxxxxx", "role": "", "region": "eu-west-1", "kind": "Domain", "namespace": "default", "name": "os-test", "is_adopted": false, "generation": 7, "json": "{\"metadata\":{\"resourceVersion\":\"152787024\"},\"spec\":{\"tags\":...,\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2022-09-16T12:03:37Z\",\"status\":\"True\",\"type\":\"ACK.ResourceSynced\"},{\"message\":\"not implemented\",\"status\":\"True\",\"type\":\"ACK.Recoverable\"}]}}"}
2022-09-16T12:03:37.511912592Z 2022-09-16T12:03:37.511Z	DEBUG	ackrt	<< kc.Patch (status)	{"account": "xxxxxxxxxxxx", "role": "", "region": "eu-west-1", "kind": "Domain", "namespace": "default", "name": "os-test", "is_adopted": false, "generation": 7}
2022-09-16T12:03:37.511923872Z 2022-09-16T12:03:37.511Z	DEBUG	ackrt	< r.patchResourceStatus	{"account": "xxxxxxxxxxxx", "role": "", "region": "eu-west-1", "kind": "Domain", "namespace": "default", "name": "os-test", "is_adopted": false, "generation": 7}
2022-09-16T12:03:37.512003724Z 2022-09-16T12:03:37.511Z	ERROR	controller.domain	Reconciler error	{"reconciler group": "opensearchservice.services.k8s.aws", "reconciler kind": "Domain", "name": "os-test", "namespace": "default", "error": "not implemented"}
2022-09-16T12:03:37.512009317Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
2022-09-16T12:03:37.512011690Z 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
2022-09-16T12:03:37.512014133Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
2022-09-16T12:03:37.512016472Z 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227

```

**Comment by A-Hilaly** [comment] 2022-09-16 14:04
Hi @shreben unfortunately updates are not support yet. Closing as this is a duplicate of https://github.com/aws-controllers-k8s/community/issues/1181
/close

**Closed by A-Hilaly** 2022-09-16 14:04 UTC
